### ISSUE TITLE
jpm sign failes

### ISSUE THREAD

**Issue by andreicristianpetcu** [gorhill/uBlock#2433]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
If I try to sign the extension with `jpm sign` it fails with an error.
I see the embeded webextensions for example are not signed and I guess they are not since the uBlock Origin devs sign the addon in AMO. If we fix this issue you can provide signed extensions just like [this one](https://andreicristianpetcu.github.io/chrome2firefox/addons/unofficial_signed_embeded_webextension_ublock_origin-1.11.3b1-fx.xpi).

### Steps for anyone to reproduce the issue

1. Install NodeJS and run `npm i -g jpm`.
2. Grab you [credentials from AMO](https://addons.mozilla.org/en-US/developers/addon/api/key/)
3. `jpm sign --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET --xpi uBlock0.webext.xpi`
Obviously replace $AMO_API_KEY and $AMO_API_SECRET from step 2.
4. Boom! Error!
`bash
JPM [error] FAIL
Error: Could not find root RDF element in install.rdf
    at /usr/lib/node_modules/jpm/lib/utils.js:202:15
    at tryCatchReject (/usr/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:592:4)
    at ContinuationTask.run (/usr/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:702:24)
    at Scheduler._drain (/usr/lib/node_modules/jpm/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/jpm/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
`
I'll send a pull request for this soon because I know the fix also :D

**Comment by andreicristianpetcu** [comment]
Aaaannd there is the pull request https://github.com/gorhill/uBlock/pull/2434

After this gets merged you can actually sign the extension as part of the build :D
